### PR TITLE
Update for 5.14.0 release

### PR DESCRIPTION
**Pull request by attilabukor**

### CODE REVIEW

**Comment by toddlipcon** [comment]
Looks fine. Have you tested this out including the quickstart VM? I'm not certain whether it is published yet, etc.

**Comment by r1pp3rj4ck** [comment]
I didn’t test the quickstart VM, sorry, I just kinda assumed we release it along with CDH. I’ll check when I get home.

**Comment by r1pp3rj4ck** [comment]
it's not out yet :/ should I revert that change for now or should we just hold on with this PR until the image is published?

**Comment by toddlipcon** [comment]
Let's just bump the maven dependency to 1.6.0 from the ASF/central repo anyway, and leave the old quickstart. New client should work OK against older clusters and a lot of people use these examples against non-quickstart deployments.

**Comment by r1pp3rj4ck** [comment]
ok, but why ASF? I mean the pom.xml has Cloudera's repo + Cloudera's quickstart is used too.

**Comment by toddlipcon** [comment]
Oh, for some reason I thought the pom was just maven central. Sure, the Cloudera repo is fine then, since this is managed in the cloudera github, not part of the ASF project.

**Comment by r1pp3rj4ck** [comment]
sorry, I was planning to wait a few days to see if the quickstart VM is updated, but I forgot about it... It still hasn't been updated though, so I reverted that part of the change

**Comment by adembo** [comment]
Looks like this stagnated, but we've stopped maintaining the quickstart VM in favor of Docker images managed in the [main Apache Kudu repository](https://github.com/apache/kudu/tree/master/docker).

**Pull request closed without merging**
